- name: Create server user
  user: name={{ server_user }} shell=/bin/bash
  sudo: yes

- name: Upload SSH public key for the server user
  authorized_key: user={{ server_user }} key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  sudo: yes

- name: Update sudoers file and validate
  lineinfile: "dest=/etc/sudoers
    insertafter=EOF
    line='{{ server_user }} ALL=(ALL) NOPASSWD: ALL'
    regexp='{{ server_user }} ALL=(ALL) NOPASSWD: ALL'
    state=present"
  sudo: true
#
#- name: Create app user
#  user: name={{ app_user }} shell=/bin/bash
#  sudo: yes
#
#- name: Upload SSH public key for the server user
#  authorized_key: user={{ app_user }} key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
#  sudo: yes

