- name: Run all scripts
  user: "{{ server_user }}"
  hosts: "{{ env }}"
  max_fail_percentage: 0
  sudo: yes
  roles:
    - python
    - app_user
    - app_prepare
    - upstart
    - deploy
  #  - upstart_restart


