# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64"

  # config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.network "private_network", ip: "192.168.33.21"

  config.ssh.forward_agent = true

  config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--rtcuseutc", "on"]
      vb.memory = 512
  end

  config.vm.provision "ansible" do |ansible|
     ansible.playbook = "vagrant.yml"
     ansible.verbose = 'vvvv'

     # Disable default limit (required with Vagrant 1.5+)
     ansible.limit = 'all'
  end

end
